- hosts: all
  tasks:
      # We can't add repositories using the ansible apt_* commands without pycurl
      # But this approach is documented below in case you're curious:

      # Now for the approach I'll recommend
      # We need to use shell (not recommended for "secure and predictable") as
      # we need the pipe to work
      # Note also, tee by default overwrites the file, so it's ok to run this
      # multiple times
      - shell: wget -O- http://neuro.debian.net/lists/precise.us-ca.full | tee /etc/apt/sources.list.d/neurodebian.sources.list
      - command: apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9
      # Note, we only want to update the cache once (in the first apt command)
      - apt: pkg=postgresql-9.1 state=latest update_cache=yes
      - name: python packages
        apt: pkg={{ item }} state=latest
        with_items:
            - python-pycurl
            - python-pip
            - python-tornado # Note - this also pulls in pycurl
            - python-zmq
            - python-jinja2
            - python-pandas
            - python-sqlalchemy
      - pip: name=ipython version=1.1
      - pip: name=vincent

      # The following would launch an ipython notebook, but we should write an
      # init.d or service script, eventually. Similarly for RStudio.
      # And these should probably not be launched by default to keep resource
      # useage down!
      # - shell: ipython notebook --no-browser --ip '*' & chdir=/vagrant/user_reports

      # CRAN
      #- apt_key: id=E084DAB9 url=http://keyserver.ubuntu.com:80 
      - apt_key: url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x51716619E084DAB9 state=present
      - apt_repository: repo='deb http://cran.cnr.berkeley.edu/bin/linux/ubuntu precise/' state=present
      - apt_repository: repo='deb-src http://cran.cnr.berkeley.edu/bin/linux/ubuntu precise/' state=present

      - name: R packages
        apt: pkg={{ item }} state=latest update_cache=yes
        with_items:
            - r-base
            - r-base-dev
            - r-base-core
            - r-recommended

      # apt_* command usage for the curious
      # Not sure if we'd need update_cache here
      # - apt: pkg=python-pycurl state=present update_cache=yes
      # - apt_repository: repo='deb http://neurodeb.pirsquared.org data main contrib non-free' state=present
      # - apt_repository: repo='deb http://neurodeb.pirsquared.org precise main contrib non-free' state=present
      # - apt_key: id=2649A5A9 url=??? # http://pgp.mit.edu doesn't work

      - name: Statistics packages
        apt: pkg={{ item }} state=latest
        with_items:
            - build-essential
            - curl
            - cython
            - git-annex
            - git-core
            - lam-runtime
            - libblas-dev
            - libopenblas-base
            - libopenblas-dev
            - mysql-client
            - sqlite3
            - tex4ht
            - texi2html
            - texlive-bibtex-extra
            - texlive-extra-utils
            - texlive-fonts-extra
            - texlive-fonts-recommended
            - texlive-formats-extra
            - texlive-generic-extra
            - texlive-generic-recommended
            - texlive-latex-base
            - texlive-latex-extra
            - texlive-latex-recommended
            - texlive-math-extra
            - texlive-plain-extra

      # We use OpenBLAS and not Atlas for BLAS. Installing OpenBLAS makes it
      # the default but doesn't switch out Atlas' lapack library as well.
      # Because Atlas' lapack references symbols in Atlas' BLAS, we have to use
      # a different lapack.
      - name: Use OpenBLAS lapack
        shell: update-alternatives --set liblapack.so.3gf /usr/lib/lapack/liblapack.so.3gf
