- hosts: all
  tasks:
      # We can't add repositories using the ansible apt_* commands without pycurl
      # But this approach is documented below in case you're curious:

      # Now for the approach I'll recommend
      # We need to use shell (not recommended for "secure and predictable") as
      # we need the pipe to work
      # Note also, tee by default overwrites the file, so it's ok to run this
      # multiple times
      - shell: wget -O- http://neuro.debian.net/lists/precise.us-ca.full | tee /etc/apt/sources.list.d/neurodebian.sources.list
      - command: apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9
      # Note, we only want to update the cache once (in the first apt command)
      - apt: pkg=postgresql-9.1 state=latest update_cache=yes
      - name: python packages
        apt: pkg={{ item }} state=latest
        with_items:
            - ipython
            - python-pandas
            - python-sqlalchemy

      # apt_* command usage for the curious
      # Not sure if we'd need update_cache here
      # - apt: pkg=python-pycurl state=present update_cache=yes
      # - apt_repository: repo='deb http://neurodeb.pirsquared.org data main contrib non-free' state=present
      # - apt_repository: repo='deb http://neurodeb.pirsquared.org precise main contrib non-free' state=present
      # - apt_key: id=2649A5A9 url=??? # http://pgp.mit.edu doesn't work
