- hosts: all
  tasks:

      # We need to use shell here (not recommended for "secure and predictable") as
      # we need the pipe to work.
      # Note also, tee overwrites the file, so this is idempotent.
      # - shell: wget -O- http://neuro.debian.net/lists/precise.us-ca.full | tee /etc/apt/sources.list.d/neurodebian.sources.list
      # - command: apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9

      # We can't add repositories using the ansible apt_* commands without
      # pycurl. Note, we only want to update the cache once (in the first apt
      # command)
      - apt: pkg=python-pycurl state=latest update_cache=yes

      # Found key via
      # http://pgp.mit.edu:11371/pks/lookup?search=neurodebian&op=vindex
      - apt_key: url=http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xA5D32F012649A5A9
      # - apt_repository: repo='deb http://neurodeb.pirsquared.org data main contrib non-free' state=present
      - apt_repository: repo='deb http://neurodeb.pirsquared.org precise main contrib non-free' state=present

      # Additional python packages
      - name: python packages
        apt: pkg={{ item }} state=latest
        with_items:
            - python-beautifulsoup
            - python-bibtex
            - python-biopython
            - python-dev
            - python-docutils
            - python-egenix-mxproxy
            - python-egenix-mxstack
            - python-egenix-mxtexttools
            - python-gadfly
            - python-gd
            - python-gdata
            - python-genetic
            - python-geoip
            - python-gpgme
            - python-htmlgen
            - python-htmltmpl
            - python-jinja2
            - python-kjbuckets
            - python-lxml
            - python-matplotlib
            - python-mvpa
            - python-mvpa-lib
            - python-mysqldb
            - python-numpy
            - python-openpyxl
            - python-pandas
            - python-pip
            - python-rpy
            - python-scipy
            - python-sqlalchemy
            - python-sqlite
            - python-tornado # Note - this also pulls in pycurl
            - python-virtualenv
            - python-xlrd
            - python-xlwt
            - python-xmpp
            - python-yaml
            - python-zmq

      - pip: name=ipython version=1.1
      - pip: name=vincent

      # The following would launch an ipython notebook, but we should write an
      # init.d or service script, eventually. Similarly for RStudio.
      # And these should probably not be launched by default to keep resource
      # useage down!
      # - shell: ipython notebook --no-browser --ip '*' & chdir=/vagrant/user_reports

      # CRAN
      # Found key via
      # http://keyserver.ubuntu.com:11371/pks/lookup?search=rutter+michael&op=vindex
      - apt_key: url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x51716619E084DAB9 state=present
      - apt_repository: repo='deb http://cran.cnr.berkeley.edu/bin/linux/ubuntu precise/' state=present
      - apt_repository: repo='deb-src http://cran.cnr.berkeley.edu/bin/linux/ubuntu precise/' state=present

      - name: R packages
        apt: pkg={{ item }} state=latest update_cache=yes
        with_items:
            - r-base
            - r-base-dev
            - r-base-core
            - r-recommended

      - name: Useful packages for data science and computation
        apt: pkg={{ item }} state=latest
        with_items:
            - build-essential
            - curl
            - cython
            - emacs
            - git-annex
            - git-core
            - lam-runtime
            - libblas-dev
            - libjpeg62 # rstudio dependency
            - libopenblas-base
            - libopenblas-dev
            - libreoffice
            - lyx
            - mysql-client
            - postgresql-9.1
            - sqlite3
            - tex4ht
            - texi2html
            - texlive-bibtex-extra
            - texlive-extra-utils
            - texlive-fonts-extra
            - texlive-fonts-recommended
            - texlive-formats-extra
            - texlive-generic-extra
            - texlive-generic-recommended
            - texlive-latex-base
            - texlive-latex-extra
            - texlive-latex-recommended
            - texlive-math-extra
            - texlive-plain-extra

      # We use OpenBLAS and not Atlas for BLAS. Installing OpenBLAS makes it
      # the default but doesn't switch out Atlas' lapack library as well.
      # Because Atlas' lapack references symbols in Atlas' BLAS, we have to use
      # a different lapack.
      - name: Use OpenBLAS lapack
        shell: update-alternatives --set liblapack.so.3gf /usr/lib/lapack/liblapack.so.3gf

      # Enthought Canopy
      #- name: download enthought canopy
      #  get_url: url=https://www.enthought.com/downloads/canopy/rh5-64/free/ dest=/tmp/canopy-rh5-64.sh mode=0755
      #- name: install enthought canopy
      #  shell: /tmp/canopy-rh5-64.sh -b -p /usr/local/canopy executable=/bin/bash creates=/usr/local/canopy
      #- name: configure enthought canopy
      #  file: path=/usr/local/canopy owner=vagrant group=vagrant recurse=yes state=directory
 
      # RStudio
      - name: Download RStudio
        command: /vagrant/provisioning/getrstudio.py creates=/tmp/rstudio-latest.deb
      - name: Install RStudio
        command: dpkg --skip-same-version -i /tmp/rstudio-latest.deb
        register: dpkg_result
        changed_when: "dpkg_result.stdout.startswith('Selecting')"
